#!/bin/bash

# To control where the generated AWK goes, edit the following line

Var="$HOME/opt/gold/lib"

hello() { cat<<EOF	
${red}au is GOLD = the Gawk Object Layer 
v0.5 (c) 2018, Tim Menzies, BSD 2-clause license${white}
EOF
}

copyright() { hello; cat <<EOF
All rights reserved.

Copyright (c) 2018, Tim Menzies
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
EOF
}

mkdir -p $Var

ltyl=$(tput setaf 11)
white=$(tput setaf 15)
red=$(tput setaf 1)

if [ ! -f .gitignore ]; then
  echo $Var > .gitignore
  git add .gitignore
fi

cat<<EOF>$Var/vimrc
        set backupdir-=.
	set backupdir^=~/tmp,/tmp
	set nocompatible              " required
	filetype plugin indent on
	set modelines=3
	set scrolloff=3
	set autoindent
	set hidden "remember ls
	set wildmenu
	set wildmode=list:longest
	set visualbell
	set ttyfast
	set backspace=indent,eol,start
	set laststatus=2
	set splitbelow
	set mouse=a
	set title
	set number
	autocmd BufEnter * cd %:p:h
	set showmatch
	set matchtime=15
	set background=light
	set syntax=on
	syntax enable
	set ignorecase
	set incsearch
	set smartcase
	set showmatch
	set hlsearch
	colorscheme delek 
	set hlsearch!
	nnoremap <F3> :set hlsearch!<CR>
	set ruler
EOF

prep() {
  for f in *.awk; do
    g="$Var/$f"
    if [ "$f" -nt "$g" ]; then
      echo "# au $f ==> $g"  >&2
      cat $f | gawk '
      BEGIN {In=1}
      gsub(/^\"\"\"/,"") { In =  1 - In }
                         { pre  = In ? "" : "##" 
    		                   print pre prep($0)
                         }
      function prep(txt) {
        if (txt ~ /^@include/) return txt
        if (txt ~ /^[ \t]*#/ ) return txt
	if (txt ~ /function has/) return txt
        txt = gensub(/\.([^0-9])([a-zA-Z0-9_]*)/, 
	      "[\"\\1\\2\"]", "g", txt)
        gsub(/__/,".",txt)
        return txt
       }
      ' $f > $g
    fi
  done
}
help() {
  hello
  cat<<-EOF
	$ltyl
	                        88          88  
	                        88          88  
	                        88          88  
	 ,adPPYb,d8  ,adPPYba,  88  ,adPPYb,88  
	a8"    \`Y88 a8"     "8a 88 a8"    \`Y88  
	8b       88 8b       d8 88 8b       88  
	"8a,   ,d88 "8a,   ,a8" 88 "8a,   ,d88  
	 \`"YbbdP"Y8  \`"YbbdP"'  88  \`"8bbdP"Y8  
	         88                             
	 aa,     88                             
	  "Y8bbdP" $white                             

	./au FILE       	run FILE.awk
	./au FILE -f tests.awk 	load FILE.awk, then run the tests
	./au ed FILE		edit FILE 
	./au ok 		run all tests
	./au zap 		delete complied files (forces recompile)
	./au pull		get from git
	./au push		send back to git
	./au license		show license
	./au help		show help

	To use the generated awk, add "$Var" to your AWKPATH.
	Note that this code cannot load any X.awk file for
	X in ed, ok, zap, pull, push, license help. 
	EOF
}

if [ -z "$1" ]; then
  hello; echo
  echo "Type './au help' for a list of options"
  prep
else
  if   [[ "$1" == "ed"      ]]; then vim -u $Var/vimrc $2
  elif [[ "$1" == "zap"     ]]; then rm $Var/*.awk
  elif [[ "$1" == "pull"    ]]; then git pull
  elif [[ "$1" == "help"    ]]; then help
  elif [[ "$1" == "license" ]]; then copyright
  elif [[ "$1" == "ok"      ]]; then bash au tests
  elif [[ "$1" == "push"    ]]; then
     git status
     git commit -am "commiting"
     git push
  else
    prep
    stem=$(basename $1 ".awk")
    shift
    f=$stem.awk
    g="$Var/$f"
    AWKPATH="$Var:./:$AWKPATH" gawk -v MAIN="$stem" -f $g $@
  fi
fi
